"use client";

import * as React from "react";
import {
  Shield,
  AlertTriangle,
  Package,
  Scale,
  ChevronLeft,
  Info,
  CheckCircle2,
  Lock,
  FileJson,
  FileText,
  Calendar,
} from "lucide-react";
import { Button } from "@/app/components/ui/button";
import { Badge } from "@/app/components/ui/badge";
import { Progress } from "@/app/components/ui/progress";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/app/components/ui/card";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/app/components/ui/tabs";
import Link from "next/link";
import type { AuditResult } from "@/app/lib/audit";

interface ReportViewProps {
  report: {
    id: string;
    model: string;
    score: number;
    createdAt: string;
    result: AuditResult;
  };
}

const severityVariant = {
  critical: "destructive",
  high: "destructive",
  medium: "warning",
  low: "secondary",
} as const;

const scoreVariant = (score: number) => {
  if (score >= 80) return "success";
  if (score >= 60) return "warning";
  return "danger";
};

function generateMarkdown(report: ReportViewProps["report"]): string {
  const { result } = report;
  const lines = [
    `# sbomit Audit Report: ${result.name}`,
    "",
    `- **Version:** ${result.version}`,
    `- **Trust Score:** ${result.score}/100`,
    `- **License:** ${result.license.type} (${result.license.compatible ? "Compatible" : "Review required"})`,
    `- **Generated:** ${new Date(report.createdAt).toLocaleString()}`,
    `- **Model:** ${report.model}`,
    "",
    "## Summary",
    "",
    result.summary,
    "",
    "## Risks",
    "",
    ...(result.risks.length === 0
      ? ["No risks identified."]
      : result.risks.map(
          (r) => `### ${r.title} (${r.severity})\n\n${r.description}`,
        )),
    "",
    "## Dependencies",
    "",
    "| Package | Version | License | Type |",
    "| ------- | ------- | ------- | ---- |",
    ...result.dependencies.map(
      (d) =>
        `| ${d.name} | ${d.version} | ${d.license} | ${d.transitive ? "Transitive" : "Direct"} |`,
    ),
    "",
    "## License Analysis",
    "",
    result.license.note,
  ];
  return lines.join("\n");
}

function downloadBlob(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function ReportView({ report }: ReportViewProps) {
  const { result } = report;
  const [activeTab, setActiveTab] = React.useState("overview");

  const handleExportMarkdown = React.useCallback(() => {
    downloadBlob(
      `sbomit-${result.name.replace(/[@/]/g, "-")}-report.md`,
      generateMarkdown(report),
      "text/markdown",
    );
  }, [report, result.name]);

  const handleExportJson = React.useCallback(() => {
    downloadBlob(
      `sbomit-${result.name.replace(/[@/]/g, "-")}-report.json`,
      JSON.stringify({ report, result }, null, 2),
      "application/json",
    );
  }, [report, result]);

  return (
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300">
            <Lock className="h-5 w-5" />
          </div>
          <div>
            <h1 className="text-2xl font-bold tracking-tight">
              Audit report for {result.name}
            </h1>
            <p className="text-sm text-muted-foreground">
              Generated by {report.model} from public library metadata.
            </p>
          </div>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleExportMarkdown}>
            <FileText className="mr-2 h-4 w-4" />
            Markdown
          </Button>
          <Button variant="outline" size="sm" onClick={handleExportJson}>
            <FileJson className="mr-2 h-4 w-4" />
            JSON
          </Button>
        </div>
      </div>

      <div className="mb-6 flex items-center gap-2 text-sm text-muted-foreground">
        <Calendar className="h-4 w-4" />
        <span>{new Date(report.createdAt).toLocaleString()}</span>
        <span className="mx-2">·</span>
        <Shield className="h-4 w-4" />
        <span>Score {report.score}/100</span>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="mb-6">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="risks">
            Risks
            <Badge variant="secondary" className="ml-2">
              {result.risks.length}
            </Badge>
          </TabsTrigger>
          <TabsTrigger value="dependencies">Dependencies</TabsTrigger>
          <TabsTrigger value="license">License</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-6">
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            <Card>
              <CardHeader className="pb-3">
                <CardDescription>Trust Score</CardDescription>
                <div className="flex items-end gap-2">
                  <CardTitle className="text-4xl">{result.score}</CardTitle>
                  <span className="text-sm text-muted-foreground">/100</span>
                </div>
              </CardHeader>
              <CardContent>
                <Progress value={result.score} variant={scoreVariant(result.score)} />
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardDescription>Version</CardDescription>
                <CardTitle className="text-2xl">{result.version}</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  Last published {result.lastPublished}
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardDescription>Weekly Downloads</CardDescription>
                <CardTitle className="text-2xl">{result.weeklyDownloads}</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">npm registry estimate</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardDescription>License</CardDescription>
                <CardTitle className="text-2xl">{result.license.type}</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  {result.license.compatible ? "Compatible" : "Review required"}
                </p>
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Info className="h-5 w-5 text-muted-foreground" />
                AI Summary
              </CardTitle>
            </CardHeader>
            <CardContent className="text-base leading-7 text-foreground">
              {result.summary}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="risks" className="space-y-4">
          {result.risks.length === 0 ? (
            <Card>
              <CardContent className="py-8 text-center text-muted-foreground">
                <CheckCircle2 className="mx-auto mb-3 h-8 w-8 text-emerald-500" />
                No risks identified in this audit.
              </CardContent>
            </Card>
          ) : (
            result.risks.map((risk, index) => (
              <Card key={index}>
                <CardHeader>
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-center gap-3">
                      <AlertTriangle className="h-5 w-5 text-amber-500" />
                      <CardTitle className="text-lg">{risk.title}</CardTitle>
                    </div>
                    <Badge variant={severityVariant[risk.severity]}>
                      {risk.severity}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">{risk.description}</p>
                </CardContent>
              </Card>
            ))
          )}
        </TabsContent>

        <TabsContent value="dependencies">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Package className="h-5 w-5 text-muted-foreground" />
                Dependency Tree
              </CardTitle>
              <CardDescription>
                Direct and transitive dependencies identified by the audit.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {result.dependencies.length === 0 ? (
                <p className="py-8 text-center text-muted-foreground">
                  No dependencies identified.
                </p>
              ) : (
                <div className="overflow-hidden rounded-lg border border-border">
                  <table className="w-full text-sm">
                    <thead className="bg-muted">
                      <tr>
                        <th className="px-4 py-3 text-left font-medium text-muted-foreground">
                          Package
                        </th>
                        <th className="px-4 py-3 text-left font-medium text-muted-foreground">
                          Version
                        </th>
                        <th className="px-4 py-3 text-left font-medium text-muted-foreground">
                          License
                        </th>
                        <th className="px-4 py-3 text-left font-medium text-muted-foreground">
                          Type
                        </th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {result.dependencies.map((dep) => (
                        <tr key={`${dep.name}@${dep.version}`}>
                          <td className="px-4 py-3 font-medium">{dep.name}</td>
                          <td className="px-4 py-3 text-muted-foreground">
                            {dep.version}
                          </td>
                          <td className="px-4 py-3">
                            <Badge variant="outline">{dep.license}</Badge>
                          </td>
                          <td className="px-4 py-3 text-muted-foreground">
                            {dep.transitive ? "Transitive" : "Direct"}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="license">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Scale className="h-5 w-5 text-muted-foreground" />
                License Analysis
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center gap-4">
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300">
                  <CheckCircle2 className="h-6 w-6" />
                </div>
                <div>
                  <p className="text-lg font-semibold">
                    {result.license.type} License
                  </p>
                  <p className="text-sm text-muted-foreground">
                    {result.license.compatible
                      ? "Compatible with most projects"
                      : "May conflict with your project license"}
                  </p>
                </div>
              </div>
              <p className="leading-7 text-muted-foreground">
                {result.license.note}
              </p>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <div className="mt-8">
        <Link
          href="/"
          className="inline-flex items-center text-sm font-medium text-muted-foreground hover:text-foreground"
        >
          <ChevronLeft className="mr-1 h-4 w-4" />
          Run another audit
        </Link>
      </div>
    </div>
  );
}
